src/Dashboard/urls.py
from django.urls import path
from .views import medicalStaff, presentation, auth, patient, medicalHistory, department, procedure, speciality, appointement, procedureApplication, prescription

urlpatterns = [
  path('', presentation.index, name='index'),
  path('dashboard', presentation.dashboard, name='dashboard'),

  path('auth/sign-in/', auth.signIn, name='sign-in'),
  path('auth/sign-out/', auth.signOut, name='sign-out'),
  path('auth/users/', auth.userList, name='user-list'),
  path('auth/users/add/', auth.addUser, name='add-user'),
  path('auth/users/edit/<str:userId>/', auth.editUser, name='edit-user'),
  path('auth/users/delete/<str:userId>/', auth.deleteUser, name='delete-user'),

  path('dashboard/patients/', patient.patientList, name='patient-list'),
  path('dashboard/patients/add/', patient.addPatient, name='add-patient'),
  path('dashboard/patients/edit/<str:patientId>/', patient.editPatient, name='edit-patient'),
  path('dashboard/patients/delete/<str:patientId>/', patient.deletePatient, name='delete-patient'),

  path('dashboard/patients/edit/<str:patientId>/history/', medicalHistory.editMedicalHistory, name='edit-medical-history'),

  path('dashboard/medical-staff/', medicalStaff.medicalStaffList, name='medical-staff-list'),
  path('dashboard/medical-staff/add/', medicalStaff.addMedicalStaff, name='add-medical-staff'),
  path('dashboard/medical-staff/edit/<str:medicalStaffId>/', medicalStaff.editMedicalStaff, name='edit-medical-staff'),
  path('dashboard/medical-staff/delete/<str:medicalStaffId>/', medicalStaff.deleteMedicalStaff, name='delete-medical-staff'),

  path('dashboard/departments/', department.departmentList, name='department-list'),
  path('dashboard/departments/add/', department.addDepartment, name='add-department'),
  path('dashboard/departments/edit/<str:departmentId>/', department.editDepartment, name='edit-department'),
  path('dashboard/departments/delete/<str:departmentId>/', department.deleteDepartment, name='delete-department'),

  path('dashboard/specialities/', speciality.specialityList, name='speciality-list'),
  path('dashboard/specialities/add/', speciality.addSpeciality, name='add-speciality'),
  path('dashboard/specialities/edit/<str:specialityId>/', speciality.editSpeciality, name='edit-speciality'),
  path('dashboard/specialities/delete/<str:specialityId>/', speciality.deleteSpeciality, name='delete-speciality'),

  path('dashboard/procedures/', procedure.procedureList, name='procedure-list'),
  path('dashboard/procedures/add/', procedure.addProcedure, name='add-procedure'),
  path('dashboard/procedures/edit/<str:procedureId>/', procedure.editProcedure, name='edit-procedure'),
  path('dashboard/procedures/delete/<str:procedureId>/', procedure.deleteProcedure, name='delete-procedure'),

  path('dashboard/appointments/patient/<str:patientId>/add/', appointement.addAppointement, name='add-appointment'),
  path('dashboard/appointments/edit/<str:appointmentId>/', appointement.editAppointment, name='edit-appointment'),
  path('dashboard/appointments/patient/<str:patientId>/', appointement.appointmentListPatient, name='appointment-list-patient'),
  path('dashboard/appointments/medical-staff/<str:medicalStaffId>/', appointement.appointmentListMedicalStaff, name='appointment-list-medical-staff'),
  path('dashboard/appointments/delete/<str:appointmentId>/', appointement.deleteAppointment, name='delete-appointment'),
  path('dashboard/appointments/apply-procedure/<str:appointmentId>/', procedureApplication.applyProcedure, name='apply-procedure'),

  path('dashboard/procedure-applications/delete/<str:procedureApplicationId>/', procedureApplication.deleteProcedureApplication, name='delete-procedure-application'),

  path('dashboard/prescriptions/patient/<str:appointmentId>/add/', prescription.addPrescription, name='add-prescription'),
  path('dashboard/prescriptions/patient/<str:prescriptionId>/edit/', prescription.editPrescription, name='edit-prescription'),
  path('dashboard/prescriptions/patient/<str:prescriptionId>/delete/', prescription.deletePrescription, name='delete-prescription'),
]

src/EClinic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('Dashboard.urls')),
]

src/Dashboard/models.py
from django.db import models
import uuid
from django.core.validators import EmailValidator, RegexValidator

# Create your models here.
class Genders(models.TextChoices):
  MALE = 'MALE'
  FEMALE = 'FEMALE'

class ProcedureType(models.TextChoices):
  MEDICAL = 'MEDICAL',
  ADMINISTRATIVE = 'ADMINISTRATIVE'

class AppointmentState(models.TextChoices):
  SCHEDULED = 'SCHEDULED'
  COMPLETED = 'COMPLETED'
  CANCELED = 'CANCELED'

class Patient(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  firstName = models.CharField(max_length=256, null=False)
  lastName = models.CharField(max_length=256, null=False)
  dateOfBirth = models.DateField(null=False)
  address = models.CharField(max_length=256, null=False)
  phoneNumber = models.CharField(max_length=20, null=False, unique=True, validators=[RegexValidator(r'^(00213|\+213|0)(5|6|7)\d{8}$')])
  email = models.CharField(max_length=254, null=False, unique=True, validators=[EmailValidator()])
  gender = models.CharField(max_length=10, choices=Genders.choices, null=False)
  createdAt = models.DateTimeField(auto_now_add=True)
  updatedAt = models.DateTimeField(auto_now=True)

  def __str__(self):
     return f"{self.lastName} {self.firstName}"

class MedicalHistory(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  patient = models.OneToOneField('Patient', on_delete=models.CASCADE)
  notes = models.TextField(null=True, blank=True)
  allergies = models.TextField(null=True, blank=True)
  surgeries = models.TextField(null=True, blank=True)
  medications = models.TextField(null=True, blank=True)
  updatedAt = models.DateTimeField(auto_now=True, blank=True)

class MedicalStaff(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  department = models.ForeignKey('Department', on_delete=models.CASCADE)
  speciality = models.ForeignKey('Speciality', on_delete=models.CASCADE)
  firstName = models.CharField(max_length=256, null=False)
  lastName = models.CharField(max_length=256, null=False)
  dateOfBirth = models.DateField(null=False)
  address = models.CharField(max_length=256, null=False)
  phoneNumber = models.CharField(max_length=20, null=False, unique=True, validators=[RegexValidator(r'^(00213|\+213|0)(5|6|7)\d{8}$')])
  email = models.CharField(max_length=254, null=False, unique=True, validators=[EmailValidator()])
  gender = models.CharField(max_length=10, choices=Genders.choices, null=False)
  createdAt = models.DateTimeField(auto_now_add=True)
  updatedAt = models.DateTimeField(auto_now=True)

  def __str__(self):
     return f"{self.lastName} {self.firstName}"

class Department(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  name = models.CharField(max_length=256, null=False, unique=True)

  def __str__(self):
     return f"{self.name}"

class Speciality(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  name = models.CharField(max_length=256, null=False, unique=True)

  def __str__(self):
     return f"{self.name}"

class Procedure(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  name = models.CharField(max_length=256, null=False, unique=True)
  department = models.ForeignKey('Department', on_delete=models.CASCADE, null=True, blank=True)
  type = models.CharField(max_length=20, choices=ProcedureType.choices, null=False)

  def __str__(self):
     return f"{self.name}"
  
class ProcedureApplication(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  appointment = models.ForeignKey('Appointment', on_delete=models.CASCADE)
  medicalStaff = models.ForeignKey('MedicalStaff', on_delete=models.CASCADE)
  procedure = models.ForeignKey('Procedure', on_delete=models.CASCADE)
  report = models.TextField(null=True, blank=True)

  class Meta:
    unique_together = ('appointment', 'medicalStaff', 'procedure')

class Appointment(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
  timestamp = models.DateTimeField(null=False)
  state = models.CharField(max_length=15, choices=AppointmentState.choices, default=AppointmentState.SCHEDULED, blank=True)
  createdAt = models.DateTimeField(auto_now_add=True)
  updatedAt = models.DateTimeField(auto_now=True)

class Prescription(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  appointment = models.ForeignKey('Appointment', on_delete=models.CASCADE)
  content = models.TextField()

src/Dashboard/forms.py
from django import forms
from .models import Patient, MedicalHistory, MedicalStaff, Department, Speciality, Procedure, Appointment, ProcedureApplication, Prescription

class SignInForm(forms.Form):
  username = forms.CharField()
  password = forms.CharField()

class SearchForm(forms.Form):
  search  = forms.CharField(required=False)

class PatientForm(forms.ModelForm):
  class Meta:
    model = Patient
    fields = '__all__'

class MedicalHistoryForm(forms.ModelForm):
  class Meta:
    model = MedicalHistory
    fields = '__all__'

class MedicalStaffForm(forms.ModelForm):
  class Meta:
    model = MedicalStaff
    fields = '__all__'

class DepartmentForm(forms.ModelForm):
  class Meta:
    model = Department
    fields = '__all__'

class SpecialityForm(forms.ModelForm):
  class Meta:
    model = Speciality
    fields = '__all__'

class ProcedureForm(forms.ModelForm):
  class Meta:
    model = Procedure
    fields = '__all__'

class ProcedureApplicationForm(forms.ModelForm):
  class Meta:
    model = ProcedureApplication
    fields = '__all__'

class AssignMedicalStaffForm(forms.Form):
  medicalStaffId = forms.CharField()
  remove = forms.BooleanField(required=False)

class AppointmentForm(forms.ModelForm):
  class Meta:
    model = Appointment
    fields = '__all__'

class PrescriptionForm(forms.ModelForm):
  class Meta:
    model = Prescription
    fields = '__all__'

src/Dashboard/views/appointement.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..forms import AppointmentForm, SearchForm
from ..models import Patient, Appointment, MedicalStaff, ProcedureApplication, Prescription
from django.db.models import Q

@login_required(login_url='sign-in')
def addAppointement(request: HttpRequest, patientId: str):
  patient = get_object_or_404(Patient, id=patientId)
  form = AppointmentForm(initial={'patient': patient})
  if request.method == 'POST':
    data = request.POST.copy() 
    data.appendlist('patient', patient)
    form = AppointmentForm(data=data)
    if form.is_valid():
      appointment = form.save()
      messages.success(request=request, message='Appointment created successfully')
      return redirect('edit-appointment', appointmentId=appointment.id)
  context = { 'form': form, 'patient': patient }
  return render(request, 'pages/appointment/add-appointment.html', context=context)

@login_required(login_url='sign-in')
def editAppointment(request: HttpRequest, appointmentId: str):
  appointment = get_object_or_404(Appointment, id=appointmentId)
  patient = get_object_or_404(Patient, id=appointment.patient.id)
  procedureApplications = ProcedureApplication.objects.filter(appointment=appointment.id).order_by('procedure')
  prescriptions = Prescription.objects.filter(appointment=appointment)

  form = AppointmentForm(instance=appointment, initial={'patient': patient})
  if request.method == 'POST':
    data = request.POST.copy() 
    data.appendlist('patient', patient)
    form = AppointmentForm(data=data, instance=appointment)
    if form.is_valid():
      form.save()
      messages.success(request=request, message='Appointment updated successfully')
      return redirect('appointment-list-patient', patientId=patient.id)
  context = { 'form': form, 'patient': patient, 'procedureApplications': procedureApplications, 'prescriptions': prescriptions, 'appointment': appointment }
  return render(request, 'pages/appointment/edit-appointment.html', context=context)

@login_required(login_url='sign-in')
def deleteAppointment(request: HttpRequest, appointmentId: str):
  appointment = get_object_or_404(Appointment, id=appointmentId)
  patient = appointment.patient
  appointment.delete()
  return redirect('appointment-list-patient', patientId=patient.id)

@login_required(login_url='sign-in')
def appointmentListMedicalStaff(request: HttpRequest, medicalStaffId: str):
  medicalStaff = get_object_or_404(MedicalStaff, id=medicalStaffId)

  procedure_applications_for_medical_staff = ProcedureApplication.objects.filter(medicalStaff=medicalStaff)
  appointments_for_medical_staff = [pa.appointment for pa in procedure_applications_for_medical_staff]

  length = len(appointments_for_medical_staff)

  context = { 'appointments': appointments_for_medical_staff, 'medicalStaff': medicalStaff, 'length': length }
  return render(request, 'pages/appointment/appointment-list-medical-staff.html', context=context)

@login_required(login_url='sign-in')
def appointmentListPatient(request: HttpRequest, patientId: str):
  patient = get_object_or_404(Patient, id=patientId)
  form = SearchForm(request.GET)
  appointments = []
  if form.is_valid():
    search = form.cleaned_data['search']
    appointments = Appointment.objects.filter(
      Q(id__icontains=search) |
      Q(timestamp__icontains=search) |
      Q(state__icontains=search),
      patient=patient,
    ).order_by('-timestamp')
  else:
    appointments = Appointment.objects.filter(
      patient=patient,
    ).order_by('-timestamp')
  context = { 'appointments': appointments, 'form': form, 'patient': patient }
  return render(request, 'pages/appointment/appointment-list-patient.html', context=context)

src/Dashboard/views/department.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..forms import SearchForm, DepartmentForm
from ..models import Department
from django.db.models import Q

# Create your views here.
@login_required(login_url='sign-in')
def addDepartment(request: HttpRequest):
  form = DepartmentForm(request.POST)
  if request.method == 'POST':
    if form.is_valid():
      form.save()
      messages.success(request=request, message='Department created successfully')
      return redirect('department-list')
  else:
    form = DepartmentForm()
  context = { 'form': form }
  return render(request, 'pages/department/add-department.html', context=context)

@login_required(login_url='sign-in')
def editDepartment(request: HttpRequest, departmentId: str):
  department = get_object_or_404(Department, id=departmentId)
  form = DepartmentForm(instance=department)
  if request.method == 'POST':
    form = DepartmentForm(data=request.POST, instance=department)
    if form.is_valid():
      form.save()
      messages.success(request=request, message='Department updated successfully')
      return redirect('department-list')
  context = { 'form': form }
  return render(request, 'pages/department/edit-department.html', context=context)

@login_required(login_url='sign-in')
def deleteDepartment(request: HttpRequest, departmentId: str):
  department = get_object_or_404(Department, id=departmentId)
  department.delete()
  return redirect('department-list')

@login_required(login_url='sign-in')
def departmentList(request: HttpRequest):
  form = SearchForm(request.GET)
  departments = []
  if form.is_valid():
    search = form.cleaned_data['search']
    departments = Department.objects.filter(
      Q(id__icontains=search) |
      Q(name__icontains=search)
    )
  else:
    departments = Department.objects.all()
  context = { 'departments': departments, 'form': form }
  return render(request, 'pages/department/department-list.html', context=context)

src/Dashboard/views/medicalHistory.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..forms import MedicalHistoryForm
from ..models import Patient, MedicalHistory

# Create your views here.
@login_required(login_url='sign-in')
def editMedicalHistory(request: HttpRequest, patientId: str):
  patient = get_object_or_404(Patient, id=patientId)
  medicalHistory = get_object_or_404(MedicalHistory, patient=patient)
  form = MedicalHistoryForm(instance=medicalHistory, initial={'patient': patient})
  if request.method == 'POST':
    data = request.POST.copy() 
    data.appendlist('patient', patient)
    form = MedicalHistoryForm(data=data, instance=medicalHistory)
    if form.is_valid():
      form.save()
      messages.success(request=request, message='Medical history updated successfully')
      return redirect('patient-list')
  context = { 'form': form, 'patient': patient }
  return render(request, 'pages/medical-history/edit-medical-history.html', context=context)

src/Dashboard/templates/pages/procedure-application/apply-procedure.html
{% extends "layouts/dashboard.html" %} 
{% load static %}
{% load widget_tweaks %}

{% block head %}
  <title>Apply procedure</title>
{% endblock head %} 

{% block dashboard_content %}
  <div class="flex flex-1 flex-col items-center pb-[5rem]">
    <div class="w-[90%] max-w-[50rem]">
      <div class="text-[30pt] font-bold"><i class="fas fa-plus text-primary mr-[1rem]"></i>Apply procedure</div>
      <div class="text-[15pt] font-semibold ml-[1rem] mb-[1rem] mt-[1rem]"><i class="fas fa-user text-primary mr-[1rem]"></i>Patient: {{patient.firstName}} {{patient.lastName}}</div>
      <div class="text-[15pt] font-semibold ml-[1rem] mb-[1rem]"><i class="fas fa-clock text-primary mr-[1rem]"></i>Appointment of: {{appointment.timestamp}}</div>

      {% if medicalStaff != None %}
        <div class="overflow-x-auto flex-1 flex items-start">
          <table class="table table-pin-rows table-pin-cols table-zebra">
            <thead>
              <tr>
                <td></td>
                <td>Id</td> 
                <td>Department</td>
                <td>Speciality</td>
                <td>First name</td> 
                <td>Last name</td> 
                <td>Date of birth</td> 
                <td>Address</td> 
                <td>Phone number</td>
                <td>Email</td>
                <td>Gender</td>
                <td>Created at</td>
                <td>Updated at</td>
              </tr>
            </thead> 
            <tbody>
              <tr>
                <td>
                  <form action="" method="post">
                    {% csrf_token %}
                    {% render_field assignMedicalStaffForm.medicalStaffId hidden="true" placeholder="Search medical staff" value=medicalStaff.id type="text" class+="input input-bordered w-full" %}
                    {% render_field assignMedicalStaffForm.remove hidden="true" checked="true" id="remove-medical-staff" %}
                    <button class="btn btn-error min-w-[7rem]"><i class="fas fa-trash"></i> Unselect</button>
                  </form>
                </td>
                <td>{{medicalStaff.id}}</td> 
                <td>{{medicalStaff.department}}</td>
                <td>{{medicalStaff.speciality}}</td>
                <td>{{medicalStaff.firstName}}</td> 
                <td>{{medicalStaff.lastName}}</td> 
                <td>{{medicalStaff.dateOfBirth}}</td> 
                <td>{{medicalStaff.address}}</td> 
                <td>{{medicalStaff.phoneNumber}}</td>
                <td>{{medicalStaff.email}}</td>
                <td>{{medicalStaff.gender}}</td>
                <td>{{medicalStaff.createdAt}}</td>
                <td>{{medicalStaff.updatedAt}}</td>
              </tr>
            </tbody> 
          </table>
        </div>
      {% endif %}

      <form class="flex flex-1 flex-col" action="" method="post">
        {% csrf_token %}
  
        {% if form.errors %}
          <div role="alert" class="alert alert-error mt-[1rem]">
            <i class="fas fa-times"></i>
            <span>{{form.errors}}</span>
          </div>
        {% endif %}
  
        
        {% if medicalStaff != None %}
          <label class="form-control w-full">
            <div class="label">
              <span class="label-text">Procedure</span>
            </div>
            {% render_field form.procedure class+="select select-bordered" %}
          </label>

          <select name="medicalStaff" required="" id="id_medicalStaff" hidden>
            <option value="{{medicalStaff.id}}">{{medicalStaff.firstName}}</option>
          </select>

          <input type="text" name="confirm" value="true" hidden>
    
          <button class="btn btn-primary mt-[2rem]"><i class="fas fa-plus"></i>Apply procedure</button>
        {% endif %}
      </form>
  
  
      {% if medicalStaff == None %}
        <div class="flex flex-1 flex-col items-center pb-[5rem] mt-[2rem]">
          <div class="flex flex-1 flex-col justify-start w-full">
            <div class="text-[23pt] font-bold"><i class="fas fa-list text-primary mr-[1rem]"></i>Select a medical staff</div>
      
            <form action="" method="get" class="mb-[1rem]">
              <label class="form-control w-full">
                <div class="label">
                  <span class="label-text"><i class="fas fa-search"></i> Search</span>
                </div>
                <div class="flex">
                  {% render_field searchForm.search placeholder="Search medical staff" type="text" class+="input input-bordered w-full" %}
                  <button class="btn btn-primary ml-[0.5rem]"><i class="fas fa-search"></i></button>
                </div>
              </label>
            </form>
      
            {% if medicalStaffList.count > 0 %}
            <div class="overflow-x-auto flex-1 flex items-start">
              <table class="table table-pin-rows table-pin-cols table-zebra">
                <thead>
                  <tr>
                    <td></td>
                    <td>Id</td> 
                    <td>Department</td>
                    <td>Speciality</td>
                    <td>First name</td> 
                    <td>Last name</td> 
                    <td>Date of birth</td> 
                    <td>Address</td> 
                    <td>Phone number</td>
                    <td>Email</td>
                    <td>Gender</td>
                    <td>Created at</td>
                    <td>Updated at</td>
                  </tr>
                </thead> 
                <tbody>
                  {% for medicalStaff in medicalStaffList %}
                    <tr>
                      <td>
                        <form action="" method="post">
                          {% csrf_token %}
                          {% render_field assignMedicalStaffForm.medicalStaffId hidden="true" placeholder="Search medical staff" value=medicalStaff.id type="text" class+="input input-bordered w-full" %}
                          {% render_field assignMedicalStaffForm.remove hidden="true" id="assign-medical-staff"  %}
                          <button class="btn btn-primary min-w-[7rem]"><i class="fas fa-check"></i> Select</button>
                        </form>
                      </td>
                      <td>{{medicalStaff.id}}</td> 
                      <td>{{medicalStaff.department}}</td>
                      <td>{{medicalStaff.speciality}}</td>
                      <td>{{medicalStaff.firstName}}</td> 
                      <td>{{medicalStaff.lastName}}</td> 
                      <td>{{medicalStaff.dateOfBirth}}</td> 
                      <td>{{medicalStaff.address}}</td> 
                      <td>{{medicalStaff.phoneNumber}}</td>
                      <td>{{medicalStaff.email}}</td>
                      <td>{{medicalStaff.gender}}</td>
                      <td>{{medicalStaff.createdAt}}</td>
                      <td>{{medicalStaff.updatedAt}}</td>
                    </tr>
                  {% endfor %}
                </tbody> 
              </table>
            </div>
            {% else %}
              <div class="flex flex-1 flex-col justify-center items-center h-full w-full">
                <img class="w-[30%]" src="{% static "assets/empty-list.svg" %}" alt="empty-list">
                <div class="text-[20pt]">The list is empty</div>
              </div>
            {% endif %}
            
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock dashboard_content %}